# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := glibrary World

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

glibrary: 
	@echo "==== Building glibrary ($(config)) ===="
	@${MAKE} --no-print-directory -C build/windows.gmake/glibrary -f Makefile

World: glibrary
	@echo "==== Building World ($(config)) ===="
	@${MAKE} --no-print-directory -C build/windows.gmake/src -f Makefile

clean:
	@${MAKE} --no-print-directory -C build/windows.gmake/glibrary -f Makefile clean
	@${MAKE} --no-print-directory -C build/windows.gmake/src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glibrary"
	@echo "   World"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
